[workspace]
members = ["test-variants"]

[package]
name = "open-dart"
version = "0.0.1"
edition = "2021"

[dependencies]
test-variants = { path = "./test-variants" }

config = "0.14.0"

derive_builder = "0.20.0"
derive_more = { version = "1.0.0", features = ["as_ref", "display", "from", "from_str"] }

bytes = "1.6.1"
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1.38.1", features = ["full"] }

anyhow = "1.0.86"
thiserror = "1.0.63"

serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

tracing = "0.1.40"
validator = { version = "0.18.1", features = ["derive"] }
static_assertions = "1.1.0"
nutype = { version = "0.5.0", features = ["serde"] }
impls = "1.0.3"
const_format = "0.2.33"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-log = "0.2.0"

pretty_assertions = { version = "1.4.0" }