[package]
name = "open-dart"
version = "0.0.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1.38.1", features = ["full"] }
derive_builder = "0.20.0"
anyhow = "1.0.86"
thiserror = "1.0.63"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
config = "0.14.0"
