[package]
name = "open-dart"
version = "0.0.1"
edition = "2021"

[dependencies]
config = "0.14.0"

derive_builder = "0.20.0"
derive_more = "0.99.18"

bytes = "1.6.1"
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1.38.1", features = ["full"] }

anyhow = "1.0.86"
thiserror = "1.0.63"

serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

tracing = "0.1.40"
validator = { version = "0.18.1", features = ["derive"] }


[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-log = "0.2.0"